In [51]:
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
from matplotlib import pyplot as plt

from PIL import Image
from numpy import asarray
import numpy as np
# load the image
image = Image.open('hideandseek.png').convert('RGBA')
dog = Image.open('dog.png').convert('RGBA')
# convert image to numpy array
data = asarray(image)
dog_data = asarray(dog)
print(type(data))
# summarize shape
print(data.shape)

# create Pillow image
image2 = Image.fromarray(data)
print(type(image2))

# summarize image details
print(image2.mode)
print(image2.size)


<class 'numpy.ndarray'>
(1000, 1000, 4)
<class 'PIL.Image.Image'>
RGBA
(1000, 1000)


In [66]:
sum((data[:,:,3] == 255).flatten())

1000000

In [40]:
print(dog_data[len(dog_data)//4:])

[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [239 239 238 255]
  [239 239 238 255]
  [239 239 238 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [239 239 238 255]
  [239 239 238 255]
  [239 239 238 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [239 239 238 255]
  [239 239 238 255]
  [239 239 238 255]]

 ...

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [239 239 238 255]
  [239 239 238 255]
  [239 239 238 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [239 239 238 255]
  [239 239 238 255]
  [239 239 238 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [239 239 238 255]
  [239 239 238 255]
  [239 239 238 255]]]
